junit.jupiter.execution.parallel.enabled=true
junit.jupiter.extensions.autodetection.enabled=true


# Execute distinct test classes in parallel, while keeping methods within a class sequential
junit.jupiter.execution.parallel.mode.default=same_thread
junit.jupiter.execution.parallel.mode.classes.default=concurrent

# Dynamic configuration strategy: uses available CPU cores to scale threads automatically
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.execution.parallel.config.dynamic.factor=1.0